import Link from "next/link";
import { ArrowLeft, ShieldCheck } from "lucide-react";
import { Brand } from "@/components/brand";
import { Button } from "@/components/ui/button";

export default function PrivacyPage() {
  return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="container flex h-16 items-center justify-between"><Brand /><Button variant="ghost" size="sm" asChild><Link href="/"><ArrowLeft className="mr-1.5 h-3.5 w-3.5" /> Back home</Link></Button></div></header><article className="container max-w-3xl py-12 sm:py-20"><div className="rounded-2xl border bg-white p-6 shadow-sm sm:p-10"><ShieldCheck className="h-8 w-8 text-indigo-600" /><p className="mt-5 text-xs font-bold uppercase tracking-[.16em] text-indigo-600">Privacy</p><h1 className="mt-2 text-4xl font-bold tracking-[-.04em] text-slate-950">Your conversations deserve care.</h1><p className="mt-3 text-sm text-slate-500">Last updated August 29, 2026</p><div className="mt-8 space-y-6 text-sm leading-7 text-slate-600"><Section title="What Garuda collects">We collect account information, business content you deliberately provide, and conversations handled by your agents. Website visitors are identified with an opaque, agent-scoped token only when the configured consent permits memory.</Section><Section title="How information is used">Information is used to operate your workspace, answer visitor questions from approved knowledge, capture leads with explicit consent, secure the service, and provide usage insights. Garuda does not sell personal information.</Section><Section title="Control and retention">Workspace owners can export or delete leads and conversations according to their configured policy. Visitors may request that remembered conversation data be removed. Production retention and subprocessor details should be finalized for your launch jurisdictions.</Section><Section title="Contact">For privacy questions or requests, contact privacy@garuda.ai.</Section></div></div></article></main>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-base font-semibold text-slate-900">{title}</h2><p className="mt-2">{children}</p></section>; }
