import Link from "next/link";
import { ArrowLeft, FileCheck2 } from "lucide-react";
import { Brand } from "@/components/brand";
import { Button } from "@/components/ui/button";

export default function TermsPage() {
  return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="container flex h-16 items-center justify-between"><Brand /><Button variant="ghost" size="sm" asChild><Link href="/"><ArrowLeft className="mr-1.5 h-3.5 w-3.5" /> Back home</Link></Button></div></header><article className="container max-w-3xl py-12 sm:py-20"><div className="rounded-2xl border bg-white p-6 shadow-sm sm:p-10"><FileCheck2 className="h-8 w-8 text-indigo-600" /><p className="mt-5 text-xs font-bold uppercase tracking-[.16em] text-indigo-600">Terms</p><h1 className="mt-2 text-4xl font-bold tracking-[-.04em] text-slate-950">Clear expectations, better service.</h1><p className="mt-3 text-sm text-slate-500">Last updated August 29, 2026</p><div className="mt-8 space-y-6 text-sm leading-7 text-slate-600"><Section title="Using Garuda">You are responsible for the content, instructions, domains, and permitted data connected to your agents. Do not use Garuda for unlawful, deceptive, abusive, or high-risk automated decisions.</Section><Section title="Subscription">The Launch plan renews monthly at the price shown during Stripe Checkout until canceled. Plan limits and included usage are shown in your billing portal. Cancellation applies at the end of the current paid period unless required otherwise by law.</Section><Section title="AI-generated responses">AI output can be incomplete or incorrect. You must review agent instructions, approved knowledge, lead-capture behavior, and sensitive use cases before publishing.</Section><Section title="Launch note">These product terms are a presentation-ready draft and should be reviewed by qualified counsel before a public production launch.</Section></div></div></article></main>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-base font-semibold text-slate-900">{title}</h2><p className="mt-2">{children}</p></section>; }
