import { Cautions, LeadRecord, NotBuiltYet } from "@/components/usecase/blocks";
import { PageShell } from "@/components/usecase/page-shell";
import { RelatedPages } from "@/components/usecase/related";
import { PointGrid, Prose, Section, StepList } from "@/components/usecase/sections";
import { pageMetadata } from "@/lib/seo";

const HREF = "/use-cases/after-hours-lead-capture";

export const metadata = pageMetadata({
  title: "Capture leads after hours with an AI website agent",
  description:
    "What a 1am website visitor should turn into by morning: how to configure the agent, where the lead actually lands, and what Garuda does not do while you are asleep.",
  path: HREF,
});

const problems = [
  {
    title: "The traffic does not respect your opening hours",
    body: "Evenings, weekends and the hour after the kids go to bed are when people research a purchase they have been putting off. Your website is open. The part of your business that answers questions is not.",
  },
  {
    title: "A contact form is a receipt, not a conversation",
    body: "It takes a name and an email and gives nothing back. The visitor learns nothing, you learn almost nothing, and both of you wait until morning to find out whether it was worth anyone’s time.",
  },
  {
    title: "By morning they have already been helped",
    body: "Not necessarily by a competitor with a better product — usually by whichever one answered. The advantage of being awake is not fairness, it is order of arrival.",
  },
  {
    title: "Most night enquiries are answerable from what you have written",
    body: "Pricing, coverage, what is included, how it works, whether you can help at all. These are the questions that keep people from converting, and the answers usually exist somewhere in your own documents already.",
  },
];

const nightSteps = [
  {
    title: "01:47 — the widget loads",
    body: "One script tag on your site renders the agent inside an isolated Shadow DOM, so it cannot inherit or leak your page styles. It only runs on the domains you approved when you published; anywhere else the session is refused.",
  },
  {
    title: "The welcome message sets expectations",
    body: "Your welcome message is stored as the opening message of the conversation. This is where you say the team is asleep, that the agent can answer now, and that a person will follow up in the morning. Honesty here converts better than pretending someone is online.",
  },
  {
    title: "It answers from your approved sources",
    body: "Each reply is generated by Google’s Gemini, called through its OpenAI-compatible API, with your approved knowledge supplied as reference data and the recent conversation for context. It answers what you gave it and should be instructed to decline the rest.",
  },
  {
    title: "After a set number of turns, it asks",
    body: "You choose how many exchanges happen before the agent offers the contact form, and you write the sentence it uses. Ask too early and it reads as a toll gate; ask after it has been genuinely useful and people answer.",
  },
  {
    title: "Consent first, then details",
    body: "The visitor has to agree explicitly before anything is stored. Without that consent Garuda refuses the capture outright — there is no quiet path that saves the details anyway. The consent and its notice version are recorded with the lead.",
  },
  {
    title: "The lead is filed with its conversation",
    body: "The captured record is stored against the conversation that produced it, so the transcript, the page the visitor started on and the contact details all sit together when you open them at eight in the morning.",
  },
];

const configuration = [
  {
    title: "Write an after-hours welcome message",
    body: "The default welcome greets a visitor as though it is the middle of the working day. Rewrite it: say what the agent can do now, what it cannot, and when a person will reply. It is the first thing every conversation contains.",
  },
  {
    title: "Tune when the form appears",
    body: "The agent offers the contact form after a number of exchanges you set. Two is usually too early for a considered purchase and about right for an emergency trade call. Pick it deliberately rather than accepting the default.",
  },
  {
    title: "Write the privacy line under the form",
    body: "The lead form carries its own privacy text and can point at your privacy policy. At 1am, with no human to ask, that sentence is the only reassurance a visitor gets before typing a phone number.",
  },
  {
    title: "Decide what it says when it does not know",
    body: "Night is when unanswerable questions arrive. The instruction you want is that it says it does not know, offers to have a person answer in the morning, and takes details — not that it guesses.",
  },
];

const leadFields = [
  { label: "Name", type: "text" as const, value: "J. Halvorsen", required: true },
  { label: "Email", type: "email" as const, value: "j.halvorsen@example.com", required: true },
  { label: "Phone", type: "telephone" as const, value: "+47 400 00 xxx" },
  {
    label: "What are you trying to do",
    type: "select" as const,
    value: "Replace an existing supplier",
    required: true,
    why: "One select turns an overnight pile into a sorted list. It is the difference between reading nine transcripts before your first coffee and reading two.",
  },
  {
    label: "Best time to call",
    type: "select" as const,
    value: "Before 10am",
    why: "Somebody who typed this at 1am has told you when they are reachable. Asking is free; guessing costs you the callback.",
  },
  { label: "Anything else", type: "textarea" as const, value: "Current contract ends in November, want to compare before renewing." },
];

const cautions = [
  {
    title: "An agent that guesses at night is worse than silence",
    body: "Nobody is watching. A confident wrong answer about price or availability will be screenshotted and quoted back to you. Instruct the agent to decline what it was not given, and test that instruction by asking it things you never told it.",
  },
  {
    title: "Overnight traffic spends your conversation allowance",
    body: "The plan includes 100 conversations per rolling 30 days. Night traffic is real traffic, so watch the number in your workspace during the first month rather than assuming the allowance is generous or tight.",
  },
  {
    title: "The widget stops if billing stops",
    body: "Widget sessions require an active subscription. If a card fails on a Friday, the agent is not answering over the weekend either. Worth knowing before you rely on it for out-of-hours coverage.",
  },
  {
    title: "Publishing is deliberate, and so is unpublishing",
    body: "An agent only serves visitors once you publish it, and only on the domains you listed — at least one is required before publishing. Nothing goes live because a draft looked finished.",
  },
];

export default function AfterHoursPage() {
  return (
    <PageShell
      crumbs={[{ label: "Home", href: "/" }, { label: "Use cases", href: "/use-cases" }, { label: "Capturing leads after hours", href: HREF }]}
      eyebrow="Use case"
      title="The enquiry that arrives at 1am, waiting for you by eight"
      lede="Not a notification that someone visited. A conversation where the visitor got real answers from your own material, agreed to be contacted, and left details that tell you what they want — filed with the transcript that produced it. This page covers how to set that up, and exactly what Garuda does not do while you are asleep."
      facts={["Consent before any contact detail is stored", "100 conversations per rolling 30 days", "$17/month"]}
      cta={{ label: "Set up an after-hours agent", href: "/auth/sign-up" }}
    >
      <Section
        id="problem"
        eyebrow="The problem"
        title="Nights and weekends are not the quiet part of the week"
        lede="For a business that sells to people with day jobs, the hours you are least able to answer are frequently the hours they are most able to ask."
      >
        <PointGrid points={problems} />
      </Section>

      <Section
        id="night"
        tone="muted"
        eyebrow="Step by step"
        title="What actually happens while you are asleep"
        lede="No part of this is speculative — it is the sequence the product runs. Reading it in order is also the fastest way to see which parts are yours to configure."
      >
        <StepList steps={nightSteps} />
      </Section>

      <Section
        id="configure"
        eyebrow="Your decisions"
        title="Four settings that decide whether the night is worth anything"
        lede="An agent published with defaults will answer questions. An agent configured for after hours will also set expectations, ask at the right moment, and know how to say it does not know."
      >
        <PointGrid points={configuration} />
      </Section>

      <Section
        id="lead"
        tone="muted"
        eyebrow="The output"
        title="What should be waiting for you"
        lede="Six fields, one of which sorts the pile and one of which tells you when to call. Contact details are stored only after the visitor explicitly agrees, and the record keeps the conversation it came from."
      >
        <LeadRecord
          heading="Overnight lead · illustrative example"
          fields={leadFields}
          consentLine="Consent recorded with the capture, including the version of the notice shown at the time."
          note="An invented example. The test of an overnight lead is simple: can you decide who to call first without opening a single transcript? If not, the form is asking the wrong questions."
        />
      </Section>

      <Section
        id="morning"
        eyebrow="Be clear about this"
        title="Where the lead is in the morning — and what will not happen overnight"
        lede="Plenty of products in this category imply a night shift that ends with your CRM updated and a meeting on your calendar. Here is the honest version."
      >
        <NotBuiltYet title="What Garuda does not do while you sleep">
          <p>
            <strong className="font-semibold text-slate-900">It does not email or text you when a lead arrives.</strong>{" "}
            Garuda sends account email — verification, password resets, the welcome message — and does not email you when
            a lead arrives. What it can do is send that lead to a signed webhook the moment it is captured, so Zapier,
            Make, or your CRM can raise the alert instead. Without a webhook configured, new leads are found by opening
            the Leads page in your workspace.
          </p>
          <p>
            <strong className="font-semibold text-slate-900">It does not book anything.</strong> The agent has no view of
            your calendar and cannot hold a slot. The most it should do is record a preferred time, which a person confirms.
          </p>
          <p>
            <strong className="font-semibold text-slate-900">It does not write to your CRM.</strong> You can connect your
            own accounts — Google Calendar, Slack, HubSpot, Salesforce, HighLevel and well over a thousand other tools —
            through Composio, and those connections are yours and scoped to your workspace. Today that is account linking:
            the agent does not yet take actions in those tools during a conversation. Treat the captured lead as the
            handover point.
          </p>
        </NotBuiltYet>
        <Prose className="mt-8">
          What you do get in the morning is the conversation itself: the messages, the page the visitor started on, and the
          lead beside them. If the visitor agreed to be remembered, coming back later resumes the same conversation for up
          to thirty days, so a follow-up visit does not start from nothing.
        </Prose>
      </Section>

      <Section
        id="cautions"
        tone="muted"
        eyebrow="Read this part"
        title="Four things worth knowing before you rely on it overnight"
      >
        <Cautions points={cautions} />
      </Section>

      <RelatedPages currentHref={HREF} />
    </PageShell>
  );
}
